### ISSUE TITLE
Gothic not launching after error in previous instance

### ISSUE THREAD

**Issue by mnaklicki** [Szmyk/gmbt#1]
## Expected Behavior
Gothic will launch again after ending with an error message before.

## Actual Behavior
Only a Gothic2.exe process is seen in Task Manager, but the game doesn't launch.

## Steps to Reproduce the Problem

  1. Launch an instance of GMBT with scripts that have an error.
  2. Close the error message (and the game with it).
  3. Try to relaunch the game again using GMBT.

## Specifications

  - Version: v1.0-rc1
  - Platform / Operating System: Windows 10
  - Gothic game version (G1 or G2): G2

**Comment by Szmyk** [comment]
Big thanks for reporting bugs of this tool, @NefariozBG! :heart: 

I am working on the new version of GMBT, with many improvements and fixed bugs. I think I will push this to repo today at the evening and I will ping you here, so you could test it again.

**Comment by Szmyk** [comment]
OK, @NefariozBG, I force-pushed the repo. Additionaly, I created release with EXE installer: https://github.com/Szmyk/gmbt/releases/tag/v0.9 (I  reduced the version number).

After installation GMBT.exe path will be set in %PATH% variable, so you could run the tool just by typing `gmbt` in the console.

I think now you can run GMBT after some errors stopping the Gothic game. I am waiting for the report :+1:.

**Comment by Szmyk** [comment]
I've just remembered - you can run GMBT with `--show-compiling-assets` parameter to see what's happening or view logs from `%APPDATA%/GMBT/logs`.

PS. If you want to talk about GMBT, see [Gitter channel](https://gitter.im/gothic-mod-build-tool/Polish_room?source=orgpage).

**Comment by mnaklicki** [comment]
This is what the commandline looks like.
![commandline](https://user-images.githubusercontent.com/11377351/34910556-be9dc362-f8af-11e7-9805-cbd7a433c385.png)

Only after the first time the game will run and after it closes, GMBT reopens the process a second time, but it uses only about 2000 K of RAM (task manager) and the game doesn't open. The only way for the game to correctly open again is to reboot the machine.

**Comment by Szmyk** [comment]
Please, send a log files from `%APPDATA%/GMBT/logs`.

**Comment by mnaklicki** [comment]
Here is my latest log:
https://pastebin.com/raw/0T4JwYGJ

**Comment by Szmyk** [comment]
I've run the GMBT in my three PC computers and it works for me on Windows 7. 

![image](https://user-images.githubusercontent.com/12484478/34910773-7a1f3f6a-f8bc-11e7-8850-4ceb63404f18.png)

I think maybe the problem is with your OS or you do not have SystemPack or something.

Try to install again all fixes - 2.6rev2, SystemPack, PlayerKit...

Also, I remember that I had some problems with running pure Gothic 2 when I had antyvirus, Steam or Skype running in the background. Try to exit these applications.

Sorry, but I cannot help you at this moment. Of course I will check it again and try to find where is the problem.

**Comment by mnaklicki** [comment]
Huh, even though I already had SystemPack, reinstalling it actually helped, and now the game actually does run again. I figured out it was definitely not a problem with GMBT when the game wouldn't even run directly from Gothic2.exe. Anyway, thanks for the help. :)

**Comment by Szmyk** [comment]
No problem. Thanks for using GMBT :heart: 

PS. Will you or your team make this "Przystan Heladii" mod by using GMBT and publish it with the tool? It would be nice to see some mod created with help of my tool :) Remember to follow [the license](https://github.com/Szmyk/gmbt/blob/master/LICENSE) of the tool xD

**Comment by mnaklicki** [comment]
Yes, we had a GitHub repo before but it was a nightmare trying to work with a couple of scripters, with having to copy the files over to the Gothic folder each time. Now we're implementing your tool for everyone who deals in some way with assets of our mod. :)

**Comment by Szmyk** [comment]
Very nice. Thanks again!

As the tool have a MIT license, mention me in the mod authors - maybe more teams will start using GMBT :smile:.

OK, I am closing this issue. If you will have some questions, less important bugs or features requests, ping me at [Gitter](https://gitter.im/gothic-mod-build-tool/Polish_room?source=orgpage).

PS. I've seen that you have compiled assets in repository. Try decompile or find non compiled assets. I think it is better and in some cases an asset can have less file size.
