### ISSUE TITLE
Gothic crashes before run

### ISSUE THREAD

**Issue by met0rii** [Szmyk/gmbt#23]
## Actual Behavior
Fatal:-1 C: maximum texture size is lower than 32. possible reasons: wrong gfx driver setup (install other driver), bad os state (try to reboot), or insufficient gfx hardware (buy better gfx card!)  .... <zTexture.cpp,#588>

Before GMBT it worked properly.

## Steps to Reproduce the Problem

  1. Fresh installation (FIX + Starter Pack + System Pack 1.8)
  2. Create directory in _work and paste files from https://github.com/Szmyk/gmbt-example-mod
  3. Change .yml  paths from `..\..\..` to `..\..`
  4. Run ./FullTest.bat

On fresh it's working, but after trying to build by GMBT i can't run game. I tried to find a solution but without any results.

## Specifications

  - Version:
  - Platform / Operating System: Windows 10 Home
  - Gothic game version (G1 or G2): G2

(attach log file which you can find in `%APPDATA%/GMBT/logs/**date**/**time**.log`)
[15-27-02.log](https://github.com/Szmyk/gmbt/files/4209972/15-27-02.log)

**Comment by Szmyk** [comment]
Hey!

Try to run Gothic2.exe as administrator. According to my experience in gothic, this solution helps in most cases.

![image](https://user-images.githubusercontent.com/12484478/74607324-59532280-50d8-11ea-93ae-8ed6a2a33d9b.png)

**Comment by met0rii** [comment]
@Szmyk thank you for fast response!

I tried change privilege level and still have the same problems.

**Comment by Szmyk** [comment]
Unfortunately I think this is not a GMBT problem. GMBT just runs Gothic with appropiate parameters and not changing the way how engine works. 

I can only point to you another solution — try to change option `VIDEO.zVidResFullscreenBPP` or `VIDEO.zTexMaxSize` in Gothic.ini file. I believe that there are many other possibile solutions provided by users of World of Gothic or theModders forums.

**Comment by met0rii** [comment]
Yeah, i saw this topics too. It's my `gothic.ini`

```
[VIDEO]

zVidDevice=0
; ... index of graphic-device beginning with zero.

zVidResFullscreenX=800
zVidResFullscreenY=600
zVidResFullscreenBPP=32
; ... used resolution

zStartupWindowed=0
; ... should the game be started as a window-application? Just for debugging!
; ... ATTENTION: Not all resolution work in window-mode!!!

zVidBrightness=0.5
; ... brightness from 0.0 (dark) to 1.0 (bright)

zVidContrast=0.5
; ... contrast from 0.0 (low contrast) to 1.0 (high contrast)

zVidGamma=0.5
; ... gamma from 0.0 (dark) to 1.0 (bright)

zTexMaxSize=16384
; ... size of texture in pixels, default is 16384 (max)
```
I tried it before, but I had this settings.

**Comment by Szmyk** [comment]
Sorry, I forgot to specify — Gothic launched by GMBT uses `Gothic_GMBT.ini`.

**Comment by met0rii** [comment]
@Szmyk - Thank you so much. It's working now. I forgot that GMBT is creating its own `ini` file! I will close issue.

**Comment by Szmyk** [comment]
I thank you very much for using GMBT :heart:
